<div>
	<h1>Admin</h1>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/people">People</a></li>
		<li><a href="<?php echo BASE_URL; ?>/users">User Accounts</a></li>
		<li><a href="<?php echo BASE_URL; ?>/committees">Committees</a></li>
		<li><a href="<?php echo BASE_URL; ?>/appointers">Appointers</a></li>
		<li><a href="<?php echo BASE_URL; ?>/requirements">Requirements</a></li>
		<li><a href="<?php echo BASE_URL; ?>/topicTypes">Legislation Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/voteTypes">Vote Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/races">Races</a></li>
		<li><a href="<?php echo BASE_URL; ?>/tags">Tags</a></li>
	</ul>
</div>
