<?php
/**
 * @copyright 2015 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
require_once __DIR__.'/civiclegislation.admin.inc';
require_once __DIR__.'/civiclegislation.fields.inc';

function civiclegislation_libraries_info()
{
    return ['chemistry' => [
        'name'             => 'COB Fork of Chemistry PHP CMIS library',
        'vendor url'       => 'http://github.com/City-of-Bloomington/chemistry-phpclient',
        'download url'     => 'http://github.com/City-of-Bloomington/chemistry-phpclient',
        'files' => [
            'php' => [
                'browser/cmis_service.php'
            ]
        ],
        'version callback' => 'chemistry_version_callback',
    ]];
}
function chemistry_version_callback() { return true; }


function civiclegislation_menu()
{
    return [
        'admin/config/services/civiclegislation' => [
            'title'            => 'Civic Legislation settings',
            'description'      => 'Settings for the boards and committees module',
            'page callback'    => 'drupal_get_form',
            'page arguments'   => ['civiclegislation_admin_form'],
            'access arguments' => ['administer site configuration'],
            'type'             => MENU_NORMAL_ITEM
        ],
        'node/%node/meetings' => [
            'title'            => 'Meeting Materials',
            'description'      => 'Minutes and Agendas for the board or commission',
            'page callback'    => 'civiclegislation_meetings',
            'page arguments'   => [1],
            'access arguments' => ['access content']
        ]
    ];
}

function civiclegislation_meetings($node, $year=null)
{
    global $base_url;
    $year = $year ? $year : date('Y');

    $html = '';
    if (!empty(   $node->field_cmis_documents['und'][0]['doctypes_meetings'])) {
        $folder = $node->field_cmis_documents['und'][0]['folder'];


        $types  = explode(',', $node->field_cmis_documents['und'][0]['doctypes_meetings']);
        $t      = [];
        foreach ($types as $type) {
            $t[] = '\''.trim($type).'\'';
        }
        $t = implode(',',$t);
        $sql = "select * from cob:meetingfile where in_tree('$folder') and cmis:objectTypeId in ($t)";

        $cmis = _civiclegislation_get_service();
        $result = $cmis->query($sql);
        #$html.= print_r($result, true);

        $dates = [];
        foreach ($result->results as $row) {
            $d = &$row->succinctProperties;
            // CMIS returns timestamps in milliseconds.  However,
            // PHP only reads timestamps in seconds.
            $date = date('Y-m-d', $d->{'cob:meetingDate'}/1000);
            $dates[$date][$d->{'cmis:objectTypeId'}][] = [
                'id'       => $d->{'cmis:versionSeriesId'},
                'filename' => $d->{'cmis:name'},
                'mimeType' => $d->{'cmis:contentStreamMimeType'}
            ];
        }
        $html.= "
        <table>
            <thead>
                <tr><th>Date</th>
        ";
                foreach ($types as $type) {
                    $html.= "<th>$type</th>";
                }
        $html.= "
                </tr>
            </thead>
            <tbody>
        ";
            foreach ($dates as $date=>$docs) {
                $html.= "<tr><td>$date</td>";
                foreach ($types as $type) {
                    $html.= "<td>";
                    if (!empty($docs[$type])) {
                        $html.= "<ul>";
                        foreach ($docs[$type] as $d) {
                            $url = "{$base_url}/{$node->nid}/meetings/download/$d[id]";
                            $html.= "<li><a href=\"$url\" class=\"$d[mimeType]\">$d[filename]</a></li>";
                        }
                        $html.= "</ul>";
                    }
                    $html.= "</td>";
                }
                $html.= "</tr>";
            }
        $html.= "
            </tbody>
        </table>
        ";

    }

    return [
        '#markup' => "<h3>Meetings</h3>$html"
    ];
}

/**
 * Instantantiates the CMISService using variables from the admin form
 *
 * @return CMISService
 */
function _civiclegislation_get_service()
{
    static $cmis;

    if (!$cmis) {
        libraries_load('chemistry');

        $cmis = new CMISService(
            variable_get('civiclegislation_url'),
            variable_get('civiclegislation_username'),
            variable_get('civiclegislation_password'),
            variable_get('civiclegislation_repositoryId')
        );
        $cmis->succinct = true;
    }
    return $cmis;
}