<div>
	<h1>Admin</h1>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/users">Users</a></li>
		<li><a href="<?php echo BASE_URL; ?>/committees">Committees</a></li>
		<li><a href="<?php echo BASE_URL; ?>/appointers">Appointers</a></li>
		<li><a href="<?php echo BASE_URL; ?>/requirements">Requirements</a></li>
		<li><a href="<?php echo BASE_URL; ?>/topicTypes">Topic Types</a></li>
		<li><a href="<?php echo BASE_URL; ?>/races">Races</a></li>
	</ul>
</div>
