<?php
/**
 * @copyright 2015-2016 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
require_once __DIR__.'/onboard.fields.inc';

function onboard_admin_form()
{
    return system_settings_form([
        'onboard_url' => [
            '#type'          => 'textfield',
            '#default_value' => variable_get('onboard_url'),
            '#title'         => 'OnBoard url',
            '#description'   => 'The URL for OnBoard',
            '#required'      => true
        ],
        'onboard_solr_url' => [
            '#type'          => 'textfield',
            '#default_value' => variable_get('onboard_solr_url'),
            '#title'         => 'Solr Server',
            '#description'   => "The URL for CMIS server's Solr index.  This is usually the same server as the CMIS endpoint.",
            '#required'      => true
        ]
    ]);
}

function onboard_menu()
{
    return [
        'admin/config/services/onboard' => [
            'title'            => 'OnBoard settings',
            'description'      => 'Settings for the boards and committees module',
            'page callback'    => 'drupal_get_form',
            'page arguments'   => ['onboard_admin_form'],
            'access arguments' => ['administer site configuration'],
            'type'             => MENU_NORMAL_ITEM
        ],
        'onboard/%node/%/%' => [
            'title callback'   => 'onboard_document_index_title',
            'title arguments'  => [1],
            'description'      => 'Browsable index of documents from Alfresco.',
            'page callback'    => 'onboard_document_index',
            'page arguments'   => [1, 2, 3],
            'access arguments' => ['access content']
        ]
    ];
}

function onboard_document_index_title($node)
{
    return $node->title;
}

function onboard_document_index($node, $field, $documentType, $year=null)
{
    $knownTypes = [
        'meetings'    => 'meeting',
        'records'     => 'record',
        'legislation' => 'legislation'
    ];

    if (!empty(   $node->{$field}['und'][0]["doctypes_$documentType"])) {
        $folder = $node->{$field}['und'][0]['folder'];

        $namespace_short = 'D:cob:';
        $namespace_long  = '{http://bloomington.in.gov/alfresco/model}';
        $dateField       = "date@sd@{$namespace_long}{$knownTypes[$documentType]}Date";
        $year = $year ? $year : date('Y');

        $types  = explode(',', $node->{$field}['und'][0]["doctypes_$documentType"]);
        $types_cmis = [];
        $types_solr = [];
        foreach ($types as $type) {
            // Quote the types for CMIS queries
            $types_cmis[] = '\''.trim($type).'\'';
            // Expand the COB namespace for Solr queries
            $types_solr[] = str_replace($namespace_short, $namespace_long, $type);
        }
        $types_cmis = implode(','   , $types_cmis);

        $cmis = _onboard_cmis_documents($folder, $types_cmis, $year);
        $solr = _onboard_solr_years    ($folder, $types_solr, $dateField);

        $solr = json_decode($solr);
        if ($solr) {
            return theme('onboard_documents', [
                'types'=>$types, 'year'=>$year, 'node'=>$node,
                'documents' => $cmis->results,
                'years'     => $solr->facet_counts->facet_ranges->$dateField->counts,
                'namespace' => $namespace_short
            ]);
        }
        else {
            return json_last_error_msg();
        }
    }
}

/**
 * @param int $committee_id
 * @return stdClass The json object
 */
function onboard_committee_info($committee_id)
{
    $url = variable_get('onboard_url').'/committees/members?format=json;committee_id='.$committee_id;
    $r   = _onboard_get($url);
    return json_decode($r);
}

/**
 * @implements hook_theme()
 * @see https://www.drupal.org/node/933976
 */
function onboard_theme()
{
    return [
        'onboard_documents'=> [
            'template' => 'onboard_documents',
            'variables' => [
                'documents'=>null, 'types'=>null, 'year'=>null, 'years'=>null, 'namespace'=>null
            ]
        ]
    ];
}


/**
 * @param string $url
 * @return string
 */
function _onboard_get($url)
{
    $session = curl_init($url);
    curl_setopt($session, CURLOPT_HEADER,         false);
    curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($session, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($session, CURLOPT_TIMEOUT,           3);
    if (substr($url, 0, 5) == 'https') {
        curl_setopt($session, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($session, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($session, CURLOPT_SSLVERSION, 3);
    }
    return curl_exec($session);
}


/**
 * Adds slashes in front of special characters used in Solr queries
 *
 * @param string $string
 * @return string
 */
function _onboard_solr_escape($string)
{
    return str_replace(
        [chr(92),          '+',  '-',  '&',  '|',  '!',  '(',  ')',  '{',  '}',  '[',  ']',  '^',  '"',  '~',  '*',  '?',  ':',  '/'],
        [chr(92).chr(92), '\+', '\-', '\&', '\|', '\!', '\(', '\)', '\{', '\}', '\[', '\]', '\^', '\"', '\~', '\*', '\?', '\:', '\/'],
        $string
    );
}

/**
 * @param string $folder The CMIS:ObjectId of a folder
 * @param array $types The array of fully namespaced names for the types
 * @param string $dateField Fully namespaced name for the date field
 * @return string The raw http response from Solr
 */
function _onboard_solr_years($folder, $types, $dateField)
{
    foreach ($types as $i=>$t) {
        $types[$i] = 'TYPE:'._onboard_solr_escape($t);
    }

    $params = [
        'q'       => '*:*',
        'start'   => 0,
        'rows'    => 0,
        'wt'      => 'json',
        'json.nl' => 'map',
        'indent'  => 'true',
        'facet'   => 'true',
        'facet.field'       => $dateField,
        'facet.range'       => $dateField,
        'facet.range.gap'   => '+1YEAR',
        'facet.range.start' => '1980-01-01T00:00:00Z',
        'facet.range.end'   => 'NOW',
        'facet.mincount'    => 1
    ];
    $p = http_build_query($params, null, '&');
    $p.='&fq='.urlencode('ANCESTOR:'._onboard_solr_escape("workspace://SpacesStore/$folder"));
    $p.='&fq='.urlencode(implode(' OR ', $types));
    $url = variable_get('onboard_solr_url')."/select?$p";
    return _onboard_get($url);
}

function _onboard_cmis_documents($folder, $types, $year)
{
    $start = strtotime("$year-01-01") * 1000;
    $end   = strtotime("$year-12-31") * 1000;

    $sql =  "select * from cob:meetingfile"
           ." where in_tree('$folder')"
           ." and cmis:objectTypeId in ($types)"
           ." and cob:meetingDate >= $start and cob:meetingDate <= $end"
           ." order by cob:meetingDate desc";

    return _cmisro_getQuery($sql);
}
