<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for CommitteeList.
 * Generated by PHPUnit on 2008-09-29 at 10:54:38.
 */
class CommitteeListTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    CommitteeList
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new CommitteeList;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testFind().
     */
    public function testFind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
