<head>
  <link rel="stylesheet" type="text/css" href="<?php echo FN1_URL; ?>/css/default.css" />
  <link rel="stylesheet" type="text/css" href="//bloomington.in.gov/static/fn1-releases/dev/css/kirkwood.css" />
  <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>/css/local/screen.css" />
  <link rel="stylesheet" type="text/css" href="<?php echo BASE_URI; ?>/css/Font-Awesome/css/font-awesome.css" />
  <link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700,600" rel="stylesheet" type="text/css">
  <title><?php echo isset($this->title) ? self::escape($this->title) : APPLICATION_NAME; ?></title>
  <script type="text/javascript">
    var APPLICATION = {
      BASE_URL: '<?php echo BASE_URL; ?>'
    };
  </script>
</head>
