<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for CommitteeList.
 * Generated by PHPUnit on 2008-09-29 at 10:54:38.
 */
class CommitteeListTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Make sure Find returns committees ordered by name
	 */
    public function testCommitteesOrderedByName()
    {
    	$committeeList = new CommitteeList();
    	$committeeList->find();
    	$this->assertEquals($committeeList->getSort(),'name');
    }
}
