<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Member.
 * Generated by PHPUnit on 2008-09-29 at 10:54:46.
 */
class MemberTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Member
     * @access protected
     */
    protected $member;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->member = new Member();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * The new member we set up is empty it should not validate
     */
    public function testValidate() {
    	try
    	{
    		$this->member->validate();
    		$this->fail('Member failed to throw a validation exception');
    	}
    	catch (Exception $e)
    	{
    		# Success
    	}
    }

    /**
     * @todo Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * Setting the seat_id requires giving a valid seat
     */
    public function testSeat_id() {
    	$this->setSeat_id(1);
    	$this->assertEquals($this->getSeat_id(),1);
    }

    /**
     * Setting the user_id requires giving a valid user
     */
    public function testGetUser_id() {
    	$this->setUser_id(1);
    	$this->assertEquals($this->getUser_id(),1);
    }

    /**
     * @todo Implement testGetTerm_start().
     */
    public function testGetTerm_start() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTerm_end().
     */
    public function testGetTerm_end() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetSeat().
     */
    public function testGetSeat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetUser().
     */
    public function testGetUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetSeat_id().
     */
    public function testSetSeat_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetUser_id().
     */
    public function testSetUser_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetSeat().
     */
    public function testSetSeat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetUser().
     */
    public function testSetUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetTerm_start().
     */
    public function testSetTerm_start() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetTerm_end().
     */
    public function testSetTerm_end() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetFirstname().
     */
    public function testGetFirstname() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetLastname().
     */
    public function testGetLastname() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetFullname().
     */
    public function testGetFullname() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
