<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for RequirementList.
 * Generated by PHPUnit on 2008-09-29 at 10:55:01.
 */
class RequirementListTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Requirements should always be ordered alphabetically
	 */
	public function testFindOrderedAlphabetically()
	{
		$list = new RequirementList();
		$list->find();
		$this->assertEquals($list->getSort(),'text');
	}
}
