<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link rel="SHORTCUT ICON" href="/favicon.ico" />
	<script type="text/javascript" src="/functions.js"></script>
	<style type="text/css" media="screen">
		@import url("/skins/external/screen.css");
	</style>
	<style type="text/css" media="print">@import url("/skins/external/print.css");</style>
	<title>Boards and Commissions Manager - City of Bloomington, Indiana</title>
</head>
<body>
<div id="banner">
	<div id="logo"><a href="http://bloomington.in.gov/boards">Boards and Commissions</a></div>
	<div id="application_name"><a href="<?php echo BASE_URL; ?>"><strong>BOARDS AND COMMISSIONS MANAGER</strong></a></div>
</div>