<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for AppointerList.
 * Generated by PHPUnit on 2008-09-29 at 10:54:27.
 */
class AppointerListTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Makes sure find returns all Appointers ordered by name
	 */
	public function testFindOrderedByName()
	{
    	$list = new AppointerList();
    	$list->find();
    	$this->assertEquals($list->getSort(),'name');
    }
}
