<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for TopicList.
 * Generated by PHPUnit on 2008-09-29 at 10:55:23.
 */
class TopicListDbTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    TopicList
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
      $dir = dirname(__FILE__);
      exec('/usr/local/mysql/bin/mysql -u '.DB_USER.' -p'.DB_PASS.' '.DB_NAME." < $dir/../testData.sql\n");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testFind().
     */
    public function testFind() {

      $PDO = Database::getConnection();
      $query = $PDO->query('select date from topics order by date desc');
      $result = $query->fetchAll();

      $list = new TopicList();
      $list->find();
      foreach($list as $i=>$topic)
	{
	  $this->assertEquals($topic->getDate('Y-m-d'),$result[$i]['date']);
	}


    }
}
?>
