<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for User.
 * Generated by PHPUnit on 2008-09-29 at 10:55:36.
 */
class UserDbTest extends PHPUnit_Framework_TestCase
{
	protected $user;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    	$this->user = new User();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    public function testUsername() {
    	$this->user->setUsername('username');
    	$this->assertEquals($this->user->getUsername(),'username');
    }

    public function testAuthenticationMethod() {
    	$this->user->setAuthenticationMethod('local');
    	$this->assertEquals($this->user->getAuthenticationMethod(),'local');
    }

    public function testFirstname() {
    	$this->user->setFirstname('firstname');
    	$this->assertEquals($this->user->getFirstname(),'firstname');
    }

    public function testLastname() {
    	$this->user->setLastname('lastname');
    	$this->assertEquals($this->user->getLastname(),'lastname');
    }

    public function testGetFullname() {
    	$this->user->setFirstname('firstname');
    	$this->user->setLastname('lastname');
    	$this->assertEquals($this->user->getFullname(),'firstname lastname');
    }

    public function testEmail() {
    	$this->user->setEmail('email');
    	$this->assertEquals($this->user->getEmail(),'email');
    }

    public function testAddress() {
    	$this->user->setAddress('address');
    	$this->assertEquals($this->user->getAddress(),'address');
    }

    public function testCity() {
    	$this->user->setCity('city');
    	$this->assertEquals($this->user->getCity(),'city');
    }

    public function testZipcode() {
    	$this->user->setZipcode('zip');
    	$this->assertEquals($this->user->getZipcode(),'zip');
    }

    public function testHomePhone() {
    	$this->user->setHomePhone('homephone');
    	$this->assertEquals($this->user->getHomePhone(),'homephone');
    }

    public function testWorkPhone() {
    	$this->user->setWorkPhone('workphone');
    	$this->assertEquals($this->user->getWorkPhone(),'workphone');
    }

    public function testAbout() {
    	$this->user->setAbout('about');
    	$this->assertEquals($this->user->getAbout(),'about');
    }

    public function testPhotoPath() {
    	$this->user->setPhotoPath('photopath');
    	$this->assertEquals($this->user->getPhotoPath(),'photopath');
    }

    /**
     * @todo Implement testSetPassword().
     */
    public function testSetPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetPasswordHash().
     */
    public function testSetPasswordHash() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetRoles().
     */
    public function testGetRoles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetRoles().
     */
    public function testSetRoles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testHasRole().
     */
    public function testHasRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPasswordHasChanged().
     */
    public function testPasswordHasChanged() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
