<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for VotingRecordList.
 * Generated by PHPUnit on 2008-09-29 at 10:55:59.
 */
class VotingRecordListDbTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    VotingRecordList
     * @access protected
     */

	protected function setUp()
	{
		$dir = dirname(__FILE__);
		exec('/usr/local/mysql/bin/mysql -u '.DB_USER.' -p'.DB_PASS.' '.DB_NAME." < $dir/../testData.sql");

	}

    /**
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testFind().
     */
    public function testFind() {
    	$PDO = Database::getConnection();
    	$query = $PDO->query('select vr.id as id from votingRecords vr left join votes v on  vr.vote_id=v.id order by v.date desc');
    	$result = $query->fetchAll();

    	$list = new VotingRecordList();
    	$list->find();
    	foreach($list as $i=>$votingRecord)
    	{
    		$this->assertEquals($votingRecord->getId(),$result[$i]['id']);
    	}
    }

}
?>
